### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by nick1543** [ethernity-cloud/ethernity-staking-dapp#20]
**Describe the bug**
Into the "Node Operator" interface in the Staking overview I choose Approved pots list. Extended staking pots have doubled buttons "Details". See the screenshot attached.

**To Reproduce**
1. Log in as Node Operator.
2. Add Base Staking Pot (I added 5928 tETNY).
3. Add Extended Staking Pots.
4. After Staker's confirmation Pending pots become Approved and Cancel button changes to Details, while the 2nd Details button stays Details as it was.

**Expected behavior**
On my opinion after Approving a pot by a Staker the Cancel button for the Node Operator should just disappear.

**Screenshots**
![testnode02_1](https://user-images.githubusercontent.com/54639140/193423703-f6e5fab8-4d45-4d67-951d-6ee44024d3d9.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home (21H2)
 - Browser: Chrome ver. 106.0.5249.91

**Additional context**

**Bug-bounty required information (optional)**
nikolka1543@gmail.com

**Comment by varvarasd** [comment]
Hi,
I will close this bug as duplicate as it's already been reported in bug [#14](https://github.com/ethernity-cloud/ethernity-staking-dapp/issues/14)
