### ISSUE TITLE
Create new staking pot

### ISSUE THREAD

**Issue by jackalx440** [ethernity-cloud/ethernity-staking-dapp#22]
![Screenshot 2022-10-01 154628](https://user-images.githubusercontent.com/114835643/193429519-78823d62-6717-491a-925b-5b8114a63e4f.png)

Hi , when Im creating a new staking pot  I will automatically change the staking amount when Im selecting the next options 👍 

Staking request type : extended staking
Staking amount  was 8024 but will change automatically to 73024 as per screenshot
Staking period - 12 months
Reward split - 60
Can staking pot be splitted - NO
Is Staking pot pre-approved - YES

**Comment by varvarasd** [comment]
Please create a new bug report with the default and correct format for bug reporting.
I will close this for incorrect reporting format.
