### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by xupypr-ypoJIor** [ethernity-cloud/ethernity-staking-dapp#27]
**Describe the bug**
Не подключается как оператор.

**To Reproduce**
1. На сайте https://staking.ethernity.cloud/staking нажимаем Connect Wallet
2. Подключается как стейкер
3. Выполняем Log out
4. Меняем сеть с тестовой Mumbai на любую другую
5. Вновь пытаемся подключиться
6. Если на баоансе есть монеты tETNY все равно будет подключаться как СТЕЙКЕР.

**Expected behavior**
Я решил, если перенести монеты с Node Wallet на Staking wallet address. Но монеты не переводятся. У оператора узла тоже могут быть свои монеты, у него должны быть возможность подключения как оператора.

**Screenshots**
![image](https://user-images.githubusercontent.com/112793303/193444563-18dd7073-189d-4e73-b76e-8c635b52a50d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Bug-bounty required information (optional)**
ibntaus@gmail.com

**Comment by varvarasd** [comment]
Hi, 
Please use only english in reporting bugs.
From my understanding, this is not a bug. The node operator is identified as having 0 ETNY currently in testing. When the dApp production build is live, in addition, it will check for at least one contract call to have been done from the given wallet to identify it as a node operator.
I am closing this as not a bug.
