### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by VladOlej** [ethernity-cloud/ethernity-staking-dapp#41]
Добрый день. Я не могу написать на английском. Но проблема в том, что нельзя подключиться мобильным метамаском. У меня есть скрин, но я не вижу чтобы его можно было прикрепить сюда.

**Comment by varvarasd** [comment]
Hi,
In the future, for your bug report to be addressed, please make sure you use the default bug reporting format and fill it in accordingly and use the English language to report.
The Staking dApp is meant for desktops only at this stage.
I am closing this as not a bug.
Thank you
