### ISSUE TITLE
Missing tokens

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#52]
**Describe the bug**
Tokens are not comming back to Availlable tokens after i cancel an offer from marketplace as staker!

**To Reproduce**
1. Go to Marketplace
2. Cancel your offer
3. Tokens are gone!

**Expected behavior**
As staker, after cancel an offer from marketplace tokens must can see in Available tokens

**Comment by varvarasd** [comment]
Hi,
You have reported this bug again on [#30](https://github.com/ethernity-cloud/ethernity-staking-dapp/issues/30).
I am closing this as duplicate.
Thank you
