### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ivanbrij** [ethernity-cloud/ethernity-staking-dapp#54]
**Describe the bug**
In the approved staking view, there are two buttons for "Details" information

**To Reproduce**
1. Go to 'approved staking'
4. See the bug

**Expected behavior**
It must show only 1 button 

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Brave

**Additional context**

**Bug-bounty required information (optional)**
Please provide your email address if you wish to join the bug-bounty: jorgebarrera85@gmail.com
<img width="756" alt="bug" src="https://user-images.githubusercontent.com/78655008/194202738-fb50c719-6852-4ed2-badc-213b8ef5869a.png">

**Comment by varvarasd** [comment]
Hi,
This bug has already been reported on [#14](https://github.com/ethernity-cloud/ethernity-staking-dapp/issues/14).
I am closing this as a duplicate.
Thank you
