### ISSUE TITLE
The balance in the "AVAILABLE TOKENS" section does not change

### ISSUE THREAD

**Issue by Vitaliy1808** [ethernity-cloud/ethernity-staking-dapp#58]
Good afternoon! When canceling a bet, the balance in the "AVAILABLE TOKENS" section does not change on the staker's wallet!

**Comment by varvarasd** [comment]
Hi,
For future reports please fill out the default bug reporting format for your report to be addressed.
This bug has already been reported on [#30](https://github.com/ethernity-cloud/ethernity-staking-dapp/issues/30) 
I am closing this as duplicate.
Thank you
