### ISSUE TITLE
Wish

### ISSUE THREAD

**Issue by Vitaliy1808** [ethernity-cloud/ethernity-staking-dapp#59]
I would also add a visual notification for a new application "Pending"
![Screenshot_3](https://user-images.githubusercontent.com/115872201/195980505-f5099fe9-8106-434b-9aa4-8f681322e6dc.png)

**Comment by varvarasd** [comment]
Hi,
I am closing this as not a bug.
We are not taking any feature suggestions at this time as our current focus is on the first release and bug fixing.
Thank you
